version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    ports:
      - 4000:4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - docs

  docs:
    build:
      context: '.'
      dockerfile: ./Dockerfile.ruby
    working_dir: /repo
    volumes:
      - .:/repo
      - docsdeps:/usr/local/bundle
    command: bundle exec jekyll serve -H 0.0.0.0

volumes:
  docsdeps:
