version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
        environment:
          BUCKET: offen-docs
          DISTRIBUTION: E2Q11JP684XRCO
    working_directory: ~/offen
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build static site
          command: make build
      - aws-cli/install
      - run:
          name: Build Deploy to S3
          command: |
            aws s3 sync --delete ./output/. s3://$BUCKET
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths "/*"

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          context: AWS
          filters:
            branches:
              only:
                - master

orbs:
  aws-cli: circleci/aws-cli@1.0.0
